#!/bin/sh

cp /phpmongodb/config.inc.php /var/www/html/config.php

sed -i \
	-e "s/'name'\s*=>\s*\"Localhost\"/'name' => \"$MONGO_SERVER\"/" \
	-e "s/'host'\s*=>\s*\"127.0.0.1\"/'host' => \"$MONGO_SERVER\"/" \
	-e "s/'port'\s*=>\s*\"27017\"/'port' => \"$MONGO_PORT\"/" \
	-e "s/'user'\s*=>\s*'admin'/'user' => '$MONGO_USERNAME'/" \
	-e "s/'password'\s*=>\s*'admin'/'password' => '$MONGO_PASSWORD'/" \
    /var/www/html/config.php

exec ./apache-run.sh
